-- TABLE POUR LES SIGNAUX D'AMOUR
-- A copier dans Supabase > SQL Editor

create table signals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender text not null -- 'Ahmed' ou 'Lilya'
);

-- Sécurité
alter table signals enable row level security;

create policy "Allow insert everyone" on signals for insert with check (true);
create policy "Allow select everyone" on signals for select using (true);
