-- COPIEZ TOUT CE CODE --

create table capsules (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null
);

alter table capsules enable row level security;

create policy "Allow delayed insert"
on capsules for insert
with check (true);

create policy "Allow read"
on capsules for select
using (true);

-- API (Cliquer sur RUN pour valider)
