-- TABLE POUR LA BUCKET LIST / TO-DO
-- A copier dans Supabase > SQL Editor

create table todos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  task text not null,
  is_completed boolean default false,
  author text
);

-- Sécurité
alter table todos enable row level security;

create policy "Allow all actions" on todos for all using (true) with check (true);
